---
- name: Apt update & upgrade
  hosts: compsec
  tasks:
    - name: Update and upgrade apt packages
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

- name: Install package manager
  hosts: compsec
  tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - curl
          - git
        state: present
    - name: Check for Homebrew binary
      ansible.builtin.stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: brew_check
    - name: Install Homebrew
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not brew_check.stat.exists
      environment:
        NONINTERACTIVE: "1"
      changed_when: false
    - name: Add brew to PATH
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
        create: true
        mode: '0644'
        state: present

- name: Install Docker
  hosts: compsec
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
    - name: Create directory for keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Add Docker repository definition
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.sources
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: {{ ansible_distribution_release }}
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Install docker from apt
      become: true
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

- name: Install kind and kubernetes-cli
  hosts: compsec
  tasks:
    - name: Update brew and all packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
    - name: Install kind
      community.general.homebrew:
        name: kind
        state: present
    - name: Install kubernetes-cli
      community.general.homebrew:
        name: kubernetes-cli
        state: present
